#!/usr/bin/bash
#
# usage: build-img path/to/verilog.v module_name

MODULES=$1
TOP=$2

pixi run yosys -p "read_verilog $MODULES; synth -top $TOP; write_json netlist.json"
pixi run npm run netlistsvg netlist.json
cp out.svg svgs/$TOP.svg
rm out.svg netlist.json
