[workspace]
authors = ["Eric Simpson <esimp12@vt.edu>"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
preview = ["pixi-build"]
platforms = ["linux-64"]

[tasks]

[package]
name = "computer"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.1.*" }

[package.build-dependencies]
iverilog = ">=11.0,<12"
yosys = ">=0.51,<0.52"
cmake = ">=3.31.6,<4"
ninja = ">=1.12.1,<2"

[dependencies]
yosys = ">=0.56,<0.57"
nodejs = ">=24.4.1,<24.5"
