[workspace]
authors = ["Eric Simpson <esimp12@vt.edu>"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
preview = ["pixi-build"]
platforms = ["linux-64"]

[tasks]

[package]
name = "computer"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.1.*" }

[package.host-dependencies]
cmake = ">=4.1.1,<5"
ninja = ">=1.13.1,<2"
yosys = ">=0.56,<0.57"
iverilog = ">=11.0,<12"
nodejs = ">=24.4.1,<24.5"
scour = ">=0.38.2,<0.39"
